### PR TITLE
Fix nested/qualified modules

### PR DESCRIPTION
**Pull request by ahmetsait**
This fixes an issue that prevented openmethods from being used in nested modules such as:
```
module some.nested.module_;

import openmethods;
mixin(registerMethods);
```

Which caused weird errors like:

mixins.txt(484,34): Error: undefined identifier `module_`
mixins.txt(485,5): Error: alias `some.nested.module_.walkNode` conflicts with alias `some.nested.module_.walkNode` at mixins.txt(484,5)
mixins.txt(485,34): Error: undefined identifier `module_`

### CODE REVIEW

**Comment by WebFreak001** [comment]
ping, about to take ownership on dub

**Comment by jll63** [comment]
Thanks for the notification. See my reply [here](https://github.com/dlang/dub-registry/issues/547#issuecomment-1666866097).

Thinking about it, I could transfer the repo to you as well, if you are interested. Can you write a paragraph or two on your motivation for using `openmethods`, and, if it is open source, show me which project(s) you used the module in?

**Comment by ahmetsait** [comment]
My use case for using openmethods was my grad project about building a simple compiler for a small C-like language. Reading [The Expression Problem and its solutions](https://eli.thegreenplace.net/2016/the-expression-problem-and-its-solutions/) convinced me openmethods was the way to go.
I didn't get a chance to publish the project but I want to do so if I get around to continue working on it again.

Having access to the original repo would allow me to retain GitHub issues and PR history so I appreciate you being onboard with this. I think you can also just give me write access instead of transferring it completely.

**Comment by jll63** [comment]
> [The Expression Problem and its solutions](https://eli.thegreenplace.net/2016/the-expression-problem-and-its-solutions/) convinced me openmethods was the way to go. I didn't get a chance to publish the project but I want to do so if I get around to continue working on it again.

This is indeed an excellent article indeed, maybe we should mention it on the landing page (and also [YOMM2](https://github.com/jll63/yomm2)'s)..

Looking at https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1030.md

> Their response was that, though it's true that Parameters!func will not work in a wrapper, it "doesn't really work now"---default arguments and storage classes must be accounted for. This can be done with string mixins, or using a technique referred to by Jean-Louis Leroy as "refraction", both of which are clumsy. So they decided that a new std.traits template and a corresponding __traits option are needed which expand into the exact function signature of another function.

The refraction trick may not be needed anymore. However, replacing it with a cleaner approach based on the new traits is probably not trivial.

**Comment by ahmetsait** [comment]
I'm not sure which trait the DIP is talking about (or whether those traits are implemented), I might need to read the openmethods.d source a bit more to understand.

**Pull request merged**
